// Builds CSS per brand and theme, DESIGN.md per brand and theme, and the Figma sync payload,
// all from the DTCG source in tokens/. Generated files carry a header saying so.
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { ROOT, loadModes, walk, aliasOf, resolveValue, publicPath } from './lib/tokens.mjs';
import { toCss, toHex } from './lib/color.mjs';
import { designMd } from './lib/design-md.mjs';
import { figmaPayload } from './lib/figma.mjs';

const HEADER = '/* Generated by scripts/build.mjs from tokens/. Do not edit. */\n';
const { modes } = loadModes();
const out = (p, s) => {
  mkdirSync(resolve(ROOT, p, '..'), { recursive: true });
  writeFileSync(resolve(ROOT, p), s);
};

export const cssName = (path) => `--${publicPath(path).replaceAll('.', '-')}`;

const dim = (v) => (typeof v === 'object' && 'unit' in v ? `${v.value}${v.unit}` : `${v}`);

// Type sizes and leading ship in rem, so text follows the visitor's browser setting and its leading
// grows with it. The source keeps px, which Figma reads; 16px is 1rem.
const REM_PATHS = /^core\.text\.(font-size|line-height)\./;
const rem = (v) =>
  typeof v === 'object' && v.unit === 'px' ? `${+(v.value / 16).toFixed(4)}rem` : dim(v);

// One CSS value per token type. Aliases become var() so the chain stays visible in the browser.
function cssValue(token, type, tree) {
  const a = aliasOf(token);
  if (a) return { value: `var(${cssName(a)})` };
  const v = token.$value;
  switch (type) {
    case 'color': {
      const hex = toHex(v);
      const modern = toCss(v);
      return modern.startsWith('#') ? { value: modern } : { value: v.alpha < 1 ? modern : hex, modern };
    }
    case 'dimension':
      return { value: dim(v) };
    case 'duration':
      return { value: dim(v) };
    case 'number':
    case 'fontWeight':
      return { value: `${v}` };
    case 'fontFamily':
      return { value: (Array.isArray(v) ? v : [v]).map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ') };
    case 'cubicBezier':
      return { value: `cubic-bezier(${v.join(', ')})` };
    case 'shadow': {
      const layers = (Array.isArray(v) ? v : [v]).map((s) => {
        const r = resolveValue(tree, s);
        const col = toCss(r.color);
        return `${r.inset ? 'inset ' : ''}${dim(r.offsetX)} ${dim(r.offsetY)} ${dim(r.blur)} ${dim(r.spread)} ${col}`;
      });
      return { value: layers.join(', ') };
    }
    case 'typography':
      return null; // expanded below
    case 'string':
      return { value: /^".*"\s+\d/.test(v) ? v : JSON.stringify(v) };
    default:
      throw new Error(`No CSS rule for $type ${type} (${JSON.stringify(v)})`);
  }
}

function typographyLines(path, token, tree) {
  const r = resolveValue(tree, token.$value);
  const ref = (k) => {
    const raw = token.$value[k];
    const a = typeof raw === 'string' && raw.match(/^\{([^}]+)\}$/);
    return a ? `var(${cssName(a[1])})` : null;
  };
  const n = cssName(path);
  const lines = [
    [`${n}-font-family`, ref('fontFamily') ?? cssValue({ $value: r.fontFamily }, 'fontFamily').value],
    [`${n}-font-size`, ref('fontSize') ?? rem(r.fontSize)],
    [`${n}-font-weight`, ref('fontWeight') ?? `${r.fontWeight}`],
    [`${n}-line-height`, ref('lineHeight') ?? rem(r.lineHeight)],
    [`${n}-letter-spacing`, ref('letterSpacing') ?? dim(r.letterSpacing)],
  ];
  const ext = token.$extensions?.['studio.atmo'] ?? {};
  if (ext.fontFeatureSettings) {
    const a = ext.fontFeatureSettings.match(/^\{([^}]+)\}$/);
    lines.push([`${n}-font-feature-settings`, a ? `var(${cssName(a[1])})` : ext.fontFeatureSettings]);
  }
  if (ext.textTransform) lines.push([`${n}-text-transform`, ext.textTransform]);
  lines.push([`${n}`, `var(${n}-font-weight) var(${n}-font-size) / var(${n}-line-height) var(${n}-font-family)`]);
  return lines;
}

function declarations(tree, filter) {
  const base = [];
  const modern = [];
  const typeRoles = tree.$extensions?.['studio.atmo']?.typeRoles;
  for (const [p, token, type] of walk(tree)) {
    const path = p.join('.');
    if (!filter(path)) continue;
    if (type === 'typography') {
      if (typeRoles && !typeRoles.includes(p.at(-1))) continue;
      for (const [k, v] of typographyLines(path, token, tree)) base.push(`  ${k}: ${v};`);
      continue;
    }
    const c = REM_PATHS.test(path) && !aliasOf(token) ? { value: rem(token.$value) } : cssValue(token, type, tree);
    base.push(`  ${cssName(path)}: ${c.value};`);
    if (c.modern) modern.push(`    ${cssName(path)}: ${c.modern};`);
  }
  return { base, modern };
}

function block(selector, { base, modern }, indent = '') {
  let s = `${indent}${selector} {\n${base.map((l) => indent + l).join('\n')}\n${indent}}\n`;
  if (modern.length) {
    s += `${indent}@supports (color: oklch(0% 0 0)) {\n${indent}  ${selector} {\n${modern
      .map((l) => indent + l)
      .join('\n')}\n${indent}  }\n${indent}}\n`;
  }
  return s;
}

const isCore = (path) => path.startsWith('core.');
const isThemed = (path) => !path.startsWith('core.');

// Reduced motion is not a mode: each duration names its reduced value in an extension.
function reduced(tree) {
  const lines = [];
  for (const [p, token] of walk(tree)) {
    const r = token.$extensions?.['studio.atmo']?.['reduced-motion'];
    if (r) lines.push(`    ${cssName(p.join('.'))}: ${r.startsWith('{') ? `var(${cssName(r.slice(1, -1))})` : r};`);
  }
  return lines.length ? `@media (prefers-reduced-motion: reduce) {\n  :root {\n${lines.join('\n')}\n  }\n}\n` : '';
}

const brands = {};
for (const [mode, { tree }] of Object.entries(modes)) {
  const [brand, theme] = [mode.replace(/-(light|dark)$/, ''), mode.match(/(light|dark)$/)[1]];
  (brands[brand] ??= {})[theme] = tree;
  // Standalone file per brand × theme: Core, then Intent and Patterns for this mode.
  out(
    `dist/css/${mode}.css`,
    HEADER + block(':root', declarations(tree, isCore)) + block(':root', declarations(tree, isThemed)) + reduced(tree),
  );
}

// Per brand, both themes: light on :root, dark by attribute or system preference.
for (const [brand, { light, dark }] of Object.entries(brands)) {
  const darkDecl = declarations(dark, isThemed);
  const css =
    HEADER +
    block(':root', declarations(light, isCore)) +
    block(':root,\n[data-theme="light"]', declarations(light, isThemed)) +
    block('[data-theme="dark"]', darkDecl) +
    `@media (prefers-color-scheme: dark) {\n` +
    block(':root:not([data-theme="light"])', darkDecl, '  ') +
    `}\n` +
    reduced(light);
  out(`dist/css/${brand}.css`, css);
  out(`dist/design/${brand}/DESIGN.md`, designMd(brand, 'light', modes[`${brand}-light`]));
  out(`dist/design/${brand}/DESIGN.dark.md`, designMd(brand, 'dark', modes[`${brand}-dark`]));
}

// The repo root carries Atmo's pair, the files people and agents look for first.
out('DESIGN.md', designMd('atmo', 'light', modes['atmo-light']));
out('DESIGN.dark.md', designMd('atmo', 'dark', modes['atmo-dark']));
out('dist/figma/sync.json', JSON.stringify(figmaPayload(modes), null, 2) + '\n');

console.log(`Built ${Object.keys(modes).length} modes: ${Object.keys(modes).join(', ')}`);
