// Compares a dump of the Figma library against dist/figma/sync.json and writes
// reports/figma-parity.md. Exits non-zero on any difference.
//   node scripts/parity.mjs [dump.json]   (default: reports/figma-dump.json)
// The dump has the payload's shape; the sync agent writes it with a read-only Plugin API script.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { ROOT } from './lib/tokens.mjs';

const want = JSON.parse(readFileSync(resolve(ROOT, 'dist/figma/sync.json'), 'utf8'));
const dumpPath = process.argv[2] ?? 'reports/figma-dump.json';
const have = JSON.parse(readFileSync(resolve(ROOT, dumpPath), 'utf8'));

const diffs = [];
const EPS = 0.6 / 255; // half an 8-bit step
const same = (a, b) => {
  if (a && typeof a === 'object' && 'alias' in a) return b && b.alias === a.alias;
  if (a && typeof a === 'object') return b && typeof b === 'object' && ['r', 'g', 'b', 'a'].every((k) => Math.abs(a[k] - b[k]) <= EPS);
  if (typeof a === 'number') return typeof b === 'number' && Math.abs(a - b) < 1e-3;
  return a === b;
};
const show = (v) => (v === undefined ? 'missing' : JSON.stringify(v));

for (const [name, { modes }] of Object.entries(want.collections)) {
  const got = have.collections?.[name];
  if (!got) diffs.push(['collection', name, 'exists', 'missing']);
  else if (JSON.stringify(got.modes) !== JSON.stringify(modes)) diffs.push(['collection', name, modes.join(', '), got.modes.join(', ')]);
}
const haveVars = new Map(have.variables.map((v) => [`${v.collection}|${v.name}`, v]));
const wantKeys = new Set();
let compared = 0;
for (const v of want.variables) {
  const key = `${v.collection}|${v.name}`;
  wantKeys.add(key);
  const h = haveVars.get(key);
  if (!h) {
    diffs.push(['variable', key, 'exists', 'missing']);
    continue;
  }
  for (const f of ['type', 'scopes', 'codeSyntax']) {
    compared++;
    if (JSON.stringify(h[f]) !== JSON.stringify(v[f])) diffs.push([f, key, show(v[f]), show(h[f])]);
  }
  for (const [mode, val] of Object.entries(v.values)) {
    compared++;
    if (!same(val, h.values?.[mode])) diffs.push(['value', `${key} @ ${mode}`, show(val), show(h.values?.[mode])]);
  }
}
for (const key of haveVars.keys()) if (!wantKeys.has(key)) diffs.push(['variable', key, 'absent', 'present in Figma']);
const haveFx = new Map((have.effectStyles ?? []).map((e) => [e.name, e]));
for (const e of want.effectStyles) {
  compared++;
  const h = haveFx.get(e.name);
  const ok = h && h.layers.length === e.layers.length && e.layers.every((l, i) =>
    ['offsetX', 'offsetY', 'blur', 'spread'].every((k) => same(l[k], h.layers[i][k])) && same(l.color, h.layers[i].color));
  if (!ok) diffs.push(['effect style', e.name, show(e.layers), show(h?.layers)]);
}

const when = have.capturedAt ?? 'unknown';
let md = `<!-- Generated by scripts/parity.mjs. Do not edit. -->\n\n# Figma parity\n\nThe Figma library against \`dist/figma/sync.json\`. Library captured ${when}.\n\n`;
md += `- **Collections:** ${Object.keys(want.collections).length}\n- **Variables:** ${want.variables.length} in code, ${have.variables.length} in Figma\n- **Effect styles:** ${want.effectStyles.length}\n- **Fields compared:** ${compared}\n- **Differences:** ${diffs.length}\n`;
if (have.notInScope?.length) md += `\n## Not in this sync\n\n${have.notInScope.map((n) => `- ${n}`).join('\n')}\n`;
if (diffs.length) md += `\n## Differences\n\n| Kind | Token | Code | Figma |\n|---|---|---|---|\n${diffs.map((d) => `| ${d.join(' | ')} |`).join('\n')}\n`;
writeFileSync(resolve(ROOT, 'reports/figma-parity.md'), md);
console.log(`Compared ${compared} fields: ${diffs.length} difference(s). Report: reports/figma-parity.md`);
for (const d of diffs.slice(0, 20)) console.log(`  ${d.join(' | ')}`);
process.exit(diffs.length ? 1 : 0);
